[build]
  publish = "public"  
  command = "npm run build"
  functions = "functions"

[build.environment]
  BUCKET_NAME = "d3simages"
  BUCKET_REGION = "us-east-2"
  ACCESS_KEY = "AKIAQ3EGPJZ643VGCE5O"
  SECRET_KEY = "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"
